[2024-10-01T13:14:15.405+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:14:15.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:14:15.417+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:14:15.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:14:15.487+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:14:15.473+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:14:16.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:14:16.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 1.178 seconds
[2024-10-01T13:14:58.541+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:14:58.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:14:58.559+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:14:58.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:14:58.583+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:14:58.579+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:14:58.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:14:58.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.092 seconds
[2024-10-01T13:15:28.978+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:15:28.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:15:28.981+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:15:28.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:15:28.995+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:15:28.992+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:15:28.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:15:29.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.053 seconds
[2024-10-01T13:15:59.168+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:15:59.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:15:59.173+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:15:59.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:15:59.196+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:15:59.191+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:15:59.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:15:59.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.092 seconds
[2024-10-01T13:16:29.290+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:16:29.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:16:29.293+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:16:29.293+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:16:29.308+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:16:29.304+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:16:29.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:16:29.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.061 seconds
[2024-10-01T13:17:00.311+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:17:00.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:17:00.315+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:17:00.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:17:00.335+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:17:00.331+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:17:00.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:17:00.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.149 seconds
[2024-10-01T13:17:30.505+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:17:30.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:17:30.510+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:17:30.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:17:30.530+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:17:30.526+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:17:30.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:17:30.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2024-10-01T13:18:00.686+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:18:00.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:18:00.692+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:18:00.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:18:00.718+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:18:00.712+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:18:00.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:18:00.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.080 seconds
[2024-10-01T13:18:31.667+0000] {processor.py:161} INFO - Started process (PID=496) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:18:31.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:18:31.671+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:18:31.671+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:18:31.695+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:18:31.689+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:18:31.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:18:31.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.078 seconds
[2024-10-01T13:19:01.988+0000] {processor.py:161} INFO - Started process (PID=552) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:19:01.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:19:01.993+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:19:01.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:19:02.013+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:19:02.008+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:19:02.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:19:02.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.073 seconds
[2024-10-01T13:19:32.143+0000] {processor.py:161} INFO - Started process (PID=608) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:19:32.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:19:32.146+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:19:32.146+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:19:32.163+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:19:32.160+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:19:32.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:19:32.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2024-10-01T13:20:03.103+0000] {processor.py:161} INFO - Started process (PID=664) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:20:03.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:20:03.106+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:20:03.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:20:03.120+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:20:03.117+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:20:03.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:20:03.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.139 seconds
[2024-10-01T13:20:33.279+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:20:33.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:20:33.282+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:20:33.282+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:20:33.298+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:20:33.295+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:20:33.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:20:33.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.083 seconds
[2024-10-01T13:21:03.412+0000] {processor.py:161} INFO - Started process (PID=776) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:21:03.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:21:03.415+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:21:03.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:21:03.429+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:21:03.426+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:21:03.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:21:03.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.105 seconds
[2024-10-01T13:21:33.825+0000] {processor.py:161} INFO - Started process (PID=832) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:21:33.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:21:33.828+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:21:33.828+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:21:33.843+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:21:33.840+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:21:33.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:21:33.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2024-10-01T13:22:04.682+0000] {processor.py:161} INFO - Started process (PID=888) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:22:04.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:22:04.686+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:22:04.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:22:04.700+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:22:04.697+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:22:04.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:22:04.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.094 seconds
[2024-10-01T13:22:35.469+0000] {processor.py:161} INFO - Started process (PID=944) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:22:35.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:22:35.490+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:22:35.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:22:35.543+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:22:35.525+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:22:35.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:22:35.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.177 seconds
[2024-10-01T13:23:06.116+0000] {processor.py:161} INFO - Started process (PID=1007) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:23:06.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:23:06.120+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:23:06.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:23:06.135+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:23:06.132+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:23:06.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:23:06.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.093 seconds
[2024-10-01T13:23:36.751+0000] {processor.py:161} INFO - Started process (PID=1063) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:23:36.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:23:36.758+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:23:36.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:23:36.790+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:23:36.779+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:23:36.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:23:36.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.089 seconds
[2024-10-01T13:24:07.584+0000] {processor.py:161} INFO - Started process (PID=1119) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:24:07.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:24:07.603+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:24:07.601+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:24:07.663+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:24:07.653+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:24:07.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:24:07.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.378 seconds
[2024-10-01T13:24:38.113+0000] {processor.py:161} INFO - Started process (PID=1175) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:24:38.115+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:24:38.120+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:24:38.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:24:38.140+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:24:38.136+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:24:38.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:24:38.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.107 seconds
[2024-10-01T13:25:08.316+0000] {processor.py:161} INFO - Started process (PID=1227) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:25:08.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:25:08.323+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:25:08.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:25:08.356+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:25:08.348+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:25:08.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:25:08.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.127 seconds
[2024-10-01T13:25:39.267+0000] {processor.py:161} INFO - Started process (PID=1283) to work on /opt/airflow/dags/dag.py
[2024-10-01T13:25:39.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-01T13:25:39.272+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:25:39.272+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-01T13:25:39.304+0000] {logging_mixin.py:188} INFO - [2024-10-01T13:25:39.297+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from email import email
ImportError: cannot import name 'email' from 'email' (/usr/local/lib/python3.8/email/__init__.py)
[2024-10-01T13:25:39.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-01T13:25:39.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.178 seconds
